# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt6 UI code generator 6.0.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Messenger(object):
    def setupUi(self, Messenger):
        Messenger.setObjectName("Messenger")
        Messenger.resize(376, 468)
        self.centralwidget = QtWidgets.QWidget(Messenger)
        self.centralwidget.setObjectName("centralwidget")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(298, 400, 61, 51))
        self.SendButton.setObjectName("SendButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textinput = QtWidgets.QTextEdit(self.centralwidget)
        self.textinput.setGeometry(QtCore.QRect(22, 410, 271, 31))
        self.textinput.setObjectName("textinput")
        self.messagesBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.messagesBrowser.setGeometry(QtCore.QRect(22, 90, 331, 301))
        self.messagesBrowser.setObjectName("messagesBrowser")
        self.nameinput = QtWidgets.QLineEdit(self.centralwidget)
        self.nameinput.setGeometry(QtCore.QRect(239, 60, 113, 21))
        self.nameinput.setObjectName("nameinput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(193, 62, 51, 16))
        self.label_2.setObjectName("label_2")
        Messenger.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Messenger)
        self.statusbar.setObjectName("statusbar")
        Messenger.setStatusBar(self.statusbar)

        self.retranslateUi(Messenger)
        QtCore.QMetaObject.connectSlotsByName(Messenger)

    def retranslateUi(self, Messenger):
        _translate = QtCore.QCoreApplication.translate
        Messenger.setWindowTitle(_translate("Messenger", "MainWindow"))
        self.SendButton.setText(_translate("Messenger", ">"))
        self.label.setText(_translate("Messenger", "LookUp"))
        self.textinput.setPlaceholderText(_translate("Messenger", "Wrtie a text..."))
        self.nameinput.setPlaceholderText(_translate("Messenger", "Name..."))
        self.label_2.setText(_translate("Messenger", "Name:"))
